#ifndef COM_PORT_DRIVER_GLOBAL_H
#define COM_PORT_DRIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COM_PORT_DRIVER_LIBRARY)
#  define COM_PORT_DRIVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COM_PORT_DRIVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COM_PORT_DRIVER_GLOBAL_H
